### PR TITLE
Fix issue with empty language pack ZIP

### LINKED ISSUE #168: Empty language pack ZIP
**Issue Overview**
After already playing around with Traduttore some time ago, I gave it a try again today and had a problem with empty language pack ZIPs. After some debugging I found out that the issue was the `.tmp` ending of the temporary ZIP file with the `ZipArchive::CREATE`.

https://github.com/wearerequired/traduttore/blob/3.0.0/inc/ZipProvider.php#L150-L152

It worked when I either created a `$temp_zip_file` with `.zip` ending or changed the `CREATE` to `OVERWRITE`.

My first try with Traduttore was on the same server, and it worked back then, so it is a little bit strange.

**To Reproduce**
In my case: run the `wp traduttore language-pack build` WP CLI command and the generated ZIP is empty.

**Versions**

* PHP: 7.3.11
* WP-CLI: 2.4.0
* GlotPress: 2.3.1
* WordPress: 5.3.2

### PR DESCRIPTION
**Pull request by florianbrinkmann**
**Description**

I changed the second parameter of `ZipArchive->open()` to `OVERWRITE` in order to fix #168.

**How has this been tested?**
With the `wp traduttore language-pack build` command. It generates an empty ZIP with `CREATE` and a correct ZIP with `OVERWRITE`.

**Types of changes**
Bug fix

**Checklist:**
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by swissspidy** [comment]
# [Codecov](https://codecov.io/gh/wearerequired/traduttore/pull/169?src=pr&el=h1) Report
> Merging [#169](https://codecov.io/gh/wearerequired/traduttore/pull/169?src=pr&el=desc) into [master](https://codecov.io/gh/wearerequired/traduttore/commit/706ea6991327d0a5bb4b7e13cab5beb733cac32c&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/wearerequired/traduttore/pull/169?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##             master     #169   +/-   ##
=========================================
  Coverage     79.63%   79.63%           
  Complexity      397      397           
=========================================
  Files            24       24           
  Lines           928      928           
=========================================
  Hits            739      739           
  Misses          189      189           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/wearerequired/traduttore/pull/169?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/wearerequired/traduttore/pull/169?src=pr&el=footer). Last update [706ea69...b87901d](https://codecov.io/gh/wearerequired/traduttore/pull/169?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

File: inc/ZipProvider.php [hunk 1]
```diff
@@ -149,7 +149,7 @@ public function generate_zip_file() : bool {
 
 		$temp_zip_file = wp_tempnam( $this->get_zip_filename() );
 
-		if ( $zip->open( $temp_zip_file, ZipArchive::CREATE ) === true ) {
+		if ( $zip->open( $temp_zip_file, ZipArchive::OVERWRITE ) === true ) {
```
Comment (ocean90) [inline inc/ZipProvider.php]: Wondering if we should use `ZIPARCHIVE::CREATE | ZIPARCHIVE::OVERWRITE`. Would that also fix your issue?

Comment (florianbrinkmann) [reply inc/ZipProvider.php]: Yes, seems to work!

**Comment by ocean90** [comment]
Thank you!

**Comment by florianbrinkmann** [comment]
You’re welcome, thanks for the fast feedback and merge!
