### PR TITLE
 Schedule language pack updates after importing originals

### LINKED ISSUE #127: Schedule a new language pack generation after originals imported
**Issue Overview**
Language packs are currently only generated on `gp_translation_saved` which is called on `$translation->save()` which doesn't cover an original that has been marked as obsolete.

**To Reproduce**
1. Remove a string from the source
2. Create a new POT file
3. Import POT file
4. See the "1 string obsoleted" message

**Expected behavior**
A new language pack is triggered.

**Additional context**
`gp_originals_imported `: https://github.com/GlotPress/GlotPress-WP/blob/2.3.1/gp-includes/things/original.php#L337-L349

### PR DESCRIPTION
**Pull request by swissspidy**
**Description**

**How has this been tested?**

**Screenshots**
If applicable, add screenshots to show the visual change.

Fixes #127.

**Types of changes**
New feature: hooks into `gp_originals_imported` to maybe schedule language pack generation.

**Checklist:**
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: inc/Plugin.php [hunk 1]
```diff
@@ -60,6 +60,32 @@ function ( GP_Translation $translation ) {
...
+		add_action(
+			'gp_originals_imported',
+			function ( $project_id, $originals_added, $originals_existing, $originals_obsoleted, $originals_fuzzied, $originals_error ) {
+				$project = ( new ProjectLocator( $project_id ) )->get_project();
+
+				if ( ! $project ) {
+					return;
+				}
+
+				if ( 0 === max( $originals_existing, $originals_obsoleted, $originals_fuzzied, $originals_error ) ) {
```
Comment (ocean90) [inline inc/Plugin.php]: Why did you choose to include ` $originals_error`  in this check? It basically means that nothing was changed.
Isn't `$originals_fuzzied` already covered by the other action since it calls `$translation->set_status()` which internally uses the `save()` method?

I think we'll find out if we have a test for each case. Ideally `$zip_provider->schedule_generation()`  is only triggered once during the whole import.

Comment (swissspidy) [reply inc/Plugin.php]: I'm not _that_ familiar with GlotPress, hence my question in https://github.com/wearerequired/traduttore/issues/127#issuecomment-439843796 about this…

Which other action are you referring to that calls `$translation->set_status()`?

> Ideally `$zip_provider->schedule_generation()` is only triggered once during the whole import.

There isn't really much overhead in calling it more than once though.

Otherwise feel free to suggest some other way to do this or to provide some tests.

**Comment by swissspidy** [comment]
@ocean90 Your insights here on what's missing would be greatly appreciated.
