### PR TITLE
Fix check for default branch on received webhook, allowing for a custom one

### LINKED ISSUE #280: Support custom branch selection in webhook handlers
The custom branch selection feature from PR #275 is not properly integrated into the webhook handlers, where the check on the received branch is still executed against the `default_branch` in the case of GitHub and GitLab:

https://github.com/wearerequired/traduttore/blob/9ee3c19ba0723e22fa39122e5116823f11e0b4c7/inc/WebhookHandler/GitHub.php#L124-L127

https://github.com/wearerequired/traduttore/blob/9ee3c19ba0723e22fa39122e5116823f11e0b4c7/inc/WebhookHandler/GitLab.php#L82-L85

### PR DESCRIPTION
**Pull request by dottxado**
**Description**

Add the filter to customize the branch to elaborate when a webhook is received. Since most of the logic is common between the handlers, it has been extracted to the Base class.

Add the repository name to the existing filter to allow resolving the project inside the filter.

**How has this been tested?**

I tested this feature locally with some limitations. I tested sending a webhook, and I can see the request is going through without errors.

**Types of changes**

Bug fix (non-breaking change which fixes an issue)
Fixes #280 

**Checklist:**
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by dottxado** [comment]
Hello @ocean90 :wave: 
Sorry for the ping....did you have the chance to review this? :bow:

File: inc/WebhookHandler/GitHub.php [hunk 1]
```diff
@@ -117,24 +118,25 @@ public function callback(): \WP_Error|\WP_REST_Response {
 		 * @var array{repository: array{ default_branch?: string, html_url: string, full_name: string, ssh_url: string, clone_url: string, private: bool }, ref: string } $params
 		 */
 
-		if ( ! isset( $params['repository']['default_branch'] ) ) {
-			return new \WP_Error( '400', 'Request incomplete', [ 'status' => 400 ] );
-		}
```
Comment (swissspidy) [inline inc/WebhookHandler/GitHub.php:122]: This check is still needed because the `default_branch` array offset might not exist according to the docblock above.

**Comment by swissspidy** [comment]
Looks like some unit tests need updating.

After that I need to defer to @ocean90 for review.

File: inc/WebhookHandler/GitHub.php (hunk 1 above)
Comment (dottxado) [reply inc/WebhookHandler/GitHub.php:122]: Hello @swissspidy :wave: 
I have improved the check [on this line](https://github.com/wearerequired/traduttore/pull/281/changes#diff-751de6b96fe9b0a5f72322f40ad3dc9bf92f0e6fcf426217070b03c052ed08f3R121) to fix the static analysis issue. I cannot return an error because, first, I need to check if the branch in the payload is a custom one, so the missing default branch is no longer a condition that leads to an error :smile:

**Comment by dottxado** [comment]
Hi there :wave: 
The PR is ready for your review @ocean90: I fixed an issue, and the tests :bow:

File: inc/Loader/Git.php [hunk 2]
```diff
@@ -51,8 +51,9 @@ public function download(): ?string {
 		 * @since 4.0.0
 		 *
 		 * @param string $branch Name of the Git branch to clone. Empty string clones the default branch.
+		 * @param string|null $repository Name of the repository. Can be used to resolve the project.
 		 */
-		$branch = apply_filters( 'traduttore.git_clone_branch', '' );
+		$branch = apply_filters( 'traduttore.git_clone_branch', '', $this->repository->get_name() );
```
Comment (ocean90) [inline inc/Loader/Git.php]: Let's pass the full repository object to the filter.

**Review by ocean90 — CHANGES_REQUESTED** [review]

**Review by ocean90 — DISMISSED** [review]

**Comment by dottxado** [comment]
Oooops sorry, I didn't notice the code sniffer error!

**Review by ocean90 — DISMISSED** [review]

**Review by ocean90 — APPROVED** [review]
