### PR TITLE
Make ProjectLocator more strict when matching paths with existing data

### LINKED ISSUE #187: Repo name/URL to project matching is too greedy
**Issue Overview**
If you have a GlotPress project with the path `foo/foo-bar` and push something to a repo name `foo`, Traduttore will update `foo/foo-bar` with the content of `foo`. Since the text domain won't match it actually deletes all originals.

**To Reproduce**
1. Create a repo `foo`
2. Create a repo `foo-bar`
3. Set up a GlotPress project for `foo-bar`
4. Push something to `foo`
5. Notice that `foo-bar` has no strings anymore

**Expected behavior**
The repo should not match partially another repo/project.

### PR DESCRIPTION
**Pull request by ocean90**
**Description**
Fixes #187.

Remove the partially matching to avoid false positives. It doesn't seem like there's a real use case for this as we have different meta keys to support searching by URL or path. @swissspidy Am I'm missing something here?

**How has this been tested?**

**Types of changes**
Bug fix

**Checklist:**
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation.

### CODE REVIEW

File: inc/ProjectLocator.php [hunk 1]
```diff
@@ -168,10 +165,14 @@ protected function find_by_repository_url( $project ): ?GP_Project {
 	protected function find_by_source_url_template( $project ): ?GP_Project {
 		global $wpdb;
 
-		$table = GP::$project->table;
+		// Make we don't match 'foo-bar' with a path 'foo'.
```
Comment (swissspidy) [inline inc/ProjectLocator.php:168]: Grammar?

**Comment by swissspidy** [comment]
This was probably done this way before we did the more robust implementation with all the useful meta keys.

**Review by swissspidy — APPROVED** [review]

File: inc/ProjectLocator.php (hunk 1 above)
Comment (ocean90) [reply inc/ProjectLocator.php]: Changed to `Make sure a URL like '…/required' doesn't match …/required-valencia/blob/…'.`

**Review by swissspidy — APPROVED** [review]
